[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--asyncio-mode=auto --import-mode=importlib --log-level=info"
pythonpath = [".", "src"]

[tool.isort]
profile = "black"
